---
- name: npm
  community.docker.docker_compose:
    pull: true
    build: true 
    project_name: npm
    definition:
      version: '3'
      services:
        app:
          image: 'jc21/nginx-proxy-manager:latest'
          restart: unless-stopped
          ports:
            - '80:80'
            - '81:81'
            - '443:443'
          # - '53:53'
          volumes: 
            - /home/{{ ansible_user_id }}/npm/data:/data
            - /home/{{ ansible_user_id }}/npm/letsencrypt:/etc/letsencrypt
      networks:
        default:
          external: true
          name: mine
