# Will need to figure out how to include more tasks.
# Tasks go here:
---

- name: Meshcentral
  ansible.builtin.include_tasks:
    file: compose-files/meshcentral.yml
- name: npm
  ansible.builtin.include_tasks:
    file: compose-files/npm.yml
